/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VolunteerRouteImport } from './routes/volunteer'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SuccessStoriesRouteImport } from './routes/success-stories'
import { Route as RefundRouteImport } from './routes/refund'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as MissionVisionRouteImport } from './routes/mission-vision'
import { Route as MembershipRouteImport } from './routes/membership'
import { Route as MediaCoverageRouteImport } from './routes/media-coverage'
import { Route as InternshipRouteImport } from './routes/internship'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as FounderRouteImport } from './routes/founder'
import { Route as EventsRouteImport } from './routes/events'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as CsrRouteImport } from './routes/csr'
import { Route as CrowdFundingRouteImport } from './routes/crowd-funding'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CausesRouteImport } from './routes/causes'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogsIndexRouteImport } from './routes/blogs.index'
import { Route as SuccessStoriesSlugRouteImport } from './routes/success-stories_.$slug'
import { Route as ProjectsSlugRouteImport } from './routes/projects_.$slug'
import { Route as EventsSlugRouteImport } from './routes/events_.$slug'
import { Route as CausesSlugRouteImport } from './routes/causes_.$slug'
import { Route as BlogsSlugRouteImport } from './routes/blogs.$slug'

const VolunteerRoute = VolunteerRouteImport.update({
  id: '/volunteer',
  path: '/volunteer',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessStoriesRoute = SuccessStoriesRouteImport.update({
  id: '/success-stories',
  path: '/success-stories',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundRoute = RefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionVisionRoute = MissionVisionRouteImport.update({
  id: '/mission-vision',
  path: '/mission-vision',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipRoute = MembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaCoverageRoute = MediaCoverageRouteImport.update({
  id: '/media-coverage',
  path: '/media-coverage',
  getParentRoute: () => rootRouteImport,
} as any)
const InternshipRoute = InternshipRouteImport.update({
  id: '/internship',
  path: '/internship',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const FounderRoute = FounderRouteImport.update({
  id: '/founder',
  path: '/founder',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const CsrRoute = CsrRouteImport.update({
  id: '/csr',
  path: '/csr',
  getParentRoute: () => rootRouteImport,
} as any)
const CrowdFundingRoute = CrowdFundingRouteImport.update({
  id: '/crowd-funding',
  path: '/crowd-funding',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CausesRoute = CausesRouteImport.update({
  id: '/causes',
  path: '/causes',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsIndexRoute = BlogsIndexRouteImport.update({
  id: '/blogs/',
  path: '/blogs/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessStoriesSlugRoute = SuccessStoriesSlugRouteImport.update({
  id: '/success-stories_/$slug',
  path: '/success-stories/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/projects_/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/events_/$slug',
  path: '/events/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CausesSlugRoute = CausesSlugRouteImport.update({
  id: '/causes_/$slug',
  path: '/causes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsSlugRoute = BlogsSlugRouteImport.update({
  id: '/blogs/$slug',
  path: '/blogs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/causes': typeof CausesRoute
  '/contact': typeof ContactRoute
  '/crowd-funding': typeof CrowdFundingRoute
  '/csr': typeof CsrRoute
  '/documents': typeof DocumentsRoute
  '/donate': typeof DonateRoute
  '/events': typeof EventsRoute
  '/founder': typeof FounderRoute
  '/gallery': typeof GalleryRoute
  '/internship': typeof InternshipRoute
  '/media-coverage': typeof MediaCoverageRoute
  '/membership': typeof MembershipRoute
  '/mission-vision': typeof MissionVisionRoute
  '/privacy': typeof PrivacyRoute
  '/programs': typeof ProgramsRoute
  '/projects': typeof ProjectsRoute
  '/refund': typeof RefundRoute
  '/success-stories': typeof SuccessStoriesRoute
  '/terms': typeof TermsRoute
  '/volunteer': typeof VolunteerRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/causes/$slug': typeof CausesSlugRoute
  '/events/$slug': typeof EventsSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/success-stories/$slug': typeof SuccessStoriesSlugRoute
  '/blogs/': typeof BlogsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/causes': typeof CausesRoute
  '/contact': typeof ContactRoute
  '/crowd-funding': typeof CrowdFundingRoute
  '/csr': typeof CsrRoute
  '/documents': typeof DocumentsRoute
  '/donate': typeof DonateRoute
  '/events': typeof EventsRoute
  '/founder': typeof FounderRoute
  '/gallery': typeof GalleryRoute
  '/internship': typeof InternshipRoute
  '/media-coverage': typeof MediaCoverageRoute
  '/membership': typeof MembershipRoute
  '/mission-vision': typeof MissionVisionRoute
  '/privacy': typeof PrivacyRoute
  '/programs': typeof ProgramsRoute
  '/projects': typeof ProjectsRoute
  '/refund': typeof RefundRoute
  '/success-stories': typeof SuccessStoriesRoute
  '/terms': typeof TermsRoute
  '/volunteer': typeof VolunteerRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/causes/$slug': typeof CausesSlugRoute
  '/events/$slug': typeof EventsSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/success-stories/$slug': typeof SuccessStoriesSlugRoute
  '/blogs': typeof BlogsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/causes': typeof CausesRoute
  '/contact': typeof ContactRoute
  '/crowd-funding': typeof CrowdFundingRoute
  '/csr': typeof CsrRoute
  '/documents': typeof DocumentsRoute
  '/donate': typeof DonateRoute
  '/events': typeof EventsRoute
  '/founder': typeof FounderRoute
  '/gallery': typeof GalleryRoute
  '/internship': typeof InternshipRoute
  '/media-coverage': typeof MediaCoverageRoute
  '/membership': typeof MembershipRoute
  '/mission-vision': typeof MissionVisionRoute
  '/privacy': typeof PrivacyRoute
  '/programs': typeof ProgramsRoute
  '/projects': typeof ProjectsRoute
  '/refund': typeof RefundRoute
  '/success-stories': typeof SuccessStoriesRoute
  '/terms': typeof TermsRoute
  '/volunteer': typeof VolunteerRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/causes_/$slug': typeof CausesSlugRoute
  '/events_/$slug': typeof EventsSlugRoute
  '/projects_/$slug': typeof ProjectsSlugRoute
  '/success-stories_/$slug': typeof SuccessStoriesSlugRoute
  '/blogs/': typeof BlogsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/careers'
    | '/causes'
    | '/contact'
    | '/crowd-funding'
    | '/csr'
    | '/documents'
    | '/donate'
    | '/events'
    | '/founder'
    | '/gallery'
    | '/internship'
    | '/media-coverage'
    | '/membership'
    | '/mission-vision'
    | '/privacy'
    | '/programs'
    | '/projects'
    | '/refund'
    | '/success-stories'
    | '/terms'
    | '/volunteer'
    | '/blogs/$slug'
    | '/causes/$slug'
    | '/events/$slug'
    | '/projects/$slug'
    | '/success-stories/$slug'
    | '/blogs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/careers'
    | '/causes'
    | '/contact'
    | '/crowd-funding'
    | '/csr'
    | '/documents'
    | '/donate'
    | '/events'
    | '/founder'
    | '/gallery'
    | '/internship'
    | '/media-coverage'
    | '/membership'
    | '/mission-vision'
    | '/privacy'
    | '/programs'
    | '/projects'
    | '/refund'
    | '/success-stories'
    | '/terms'
    | '/volunteer'
    | '/blogs/$slug'
    | '/causes/$slug'
    | '/events/$slug'
    | '/projects/$slug'
    | '/success-stories/$slug'
    | '/blogs'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/careers'
    | '/causes'
    | '/contact'
    | '/crowd-funding'
    | '/csr'
    | '/documents'
    | '/donate'
    | '/events'
    | '/founder'
    | '/gallery'
    | '/internship'
    | '/media-coverage'
    | '/membership'
    | '/mission-vision'
    | '/privacy'
    | '/programs'
    | '/projects'
    | '/refund'
    | '/success-stories'
    | '/terms'
    | '/volunteer'
    | '/blogs/$slug'
    | '/causes_/$slug'
    | '/events_/$slug'
    | '/projects_/$slug'
    | '/success-stories_/$slug'
    | '/blogs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CareersRoute: typeof CareersRoute
  CausesRoute: typeof CausesRoute
  ContactRoute: typeof ContactRoute
  CrowdFundingRoute: typeof CrowdFundingRoute
  CsrRoute: typeof CsrRoute
  DocumentsRoute: typeof DocumentsRoute
  DonateRoute: typeof DonateRoute
  EventsRoute: typeof EventsRoute
  FounderRoute: typeof FounderRoute
  GalleryRoute: typeof GalleryRoute
  InternshipRoute: typeof InternshipRoute
  MediaCoverageRoute: typeof MediaCoverageRoute
  MembershipRoute: typeof MembershipRoute
  MissionVisionRoute: typeof MissionVisionRoute
  PrivacyRoute: typeof PrivacyRoute
  ProgramsRoute: typeof ProgramsRoute
  ProjectsRoute: typeof ProjectsRoute
  RefundRoute: typeof RefundRoute
  SuccessStoriesRoute: typeof SuccessStoriesRoute
  TermsRoute: typeof TermsRoute
  VolunteerRoute: typeof VolunteerRoute
  BlogsSlugRoute: typeof BlogsSlugRoute
  CausesSlugRoute: typeof CausesSlugRoute
  EventsSlugRoute: typeof EventsSlugRoute
  ProjectsSlugRoute: typeof ProjectsSlugRoute
  SuccessStoriesSlugRoute: typeof SuccessStoriesSlugRoute
  BlogsIndexRoute: typeof BlogsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/volunteer': {
      id: '/volunteer'
      path: '/volunteer'
      fullPath: '/volunteer'
      preLoaderRoute: typeof VolunteerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success-stories': {
      id: '/success-stories'
      path: '/success-stories'
      fullPath: '/success-stories'
      preLoaderRoute: typeof SuccessStoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund': {
      id: '/refund'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof RefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mission-vision': {
      id: '/mission-vision'
      path: '/mission-vision'
      fullPath: '/mission-vision'
      preLoaderRoute: typeof MissionVisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership': {
      id: '/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof MembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media-coverage': {
      id: '/media-coverage'
      path: '/media-coverage'
      fullPath: '/media-coverage'
      preLoaderRoute: typeof MediaCoverageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internship': {
      id: '/internship'
      path: '/internship'
      fullPath: '/internship'
      preLoaderRoute: typeof InternshipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founder': {
      id: '/founder'
      path: '/founder'
      fullPath: '/founder'
      preLoaderRoute: typeof FounderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/csr': {
      id: '/csr'
      path: '/csr'
      fullPath: '/csr'
      preLoaderRoute: typeof CsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crowd-funding': {
      id: '/crowd-funding'
      path: '/crowd-funding'
      fullPath: '/crowd-funding'
      preLoaderRoute: typeof CrowdFundingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/causes': {
      id: '/causes'
      path: '/causes'
      fullPath: '/causes'
      preLoaderRoute: typeof CausesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/': {
      id: '/blogs/'
      path: '/blogs'
      fullPath: '/blogs/'
      preLoaderRoute: typeof BlogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success-stories_/$slug': {
      id: '/success-stories_/$slug'
      path: '/success-stories/$slug'
      fullPath: '/success-stories/$slug'
      preLoaderRoute: typeof SuccessStoriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects_/$slug': {
      id: '/projects_/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events_/$slug': {
      id: '/events_/$slug'
      path: '/events/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/causes_/$slug': {
      id: '/causes_/$slug'
      path: '/causes/$slug'
      fullPath: '/causes/$slug'
      preLoaderRoute: typeof CausesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/$slug': {
      id: '/blogs/$slug'
      path: '/blogs/$slug'
      fullPath: '/blogs/$slug'
      preLoaderRoute: typeof BlogsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CareersRoute: CareersRoute,
  CausesRoute: CausesRoute,
  ContactRoute: ContactRoute,
  CrowdFundingRoute: CrowdFundingRoute,
  CsrRoute: CsrRoute,
  DocumentsRoute: DocumentsRoute,
  DonateRoute: DonateRoute,
  EventsRoute: EventsRoute,
  FounderRoute: FounderRoute,
  GalleryRoute: GalleryRoute,
  InternshipRoute: InternshipRoute,
  MediaCoverageRoute: MediaCoverageRoute,
  MembershipRoute: MembershipRoute,
  MissionVisionRoute: MissionVisionRoute,
  PrivacyRoute: PrivacyRoute,
  ProgramsRoute: ProgramsRoute,
  ProjectsRoute: ProjectsRoute,
  RefundRoute: RefundRoute,
  SuccessStoriesRoute: SuccessStoriesRoute,
  TermsRoute: TermsRoute,
  VolunteerRoute: VolunteerRoute,
  BlogsSlugRoute: BlogsSlugRoute,
  CausesSlugRoute: CausesSlugRoute,
  EventsSlugRoute: EventsSlugRoute,
  ProjectsSlugRoute: ProjectsSlugRoute,
  SuccessStoriesSlugRoute: SuccessStoriesSlugRoute,
  BlogsIndexRoute: BlogsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
